// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS02rM9SjAkUrkkqVegagZcIJUsHHQeOE',
    appId: '1:872488541859:web:14fef5479118af77ae6916',
    messagingSenderId: '872488541859',
    projectId: 'my-ecom-cr007',
    authDomain: 'my-ecom-cr007.firebaseapp.com',
    storageBucket: 'my-ecom-cr007.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDJAFBvWSDOgL2T0z-ZPCKI_hEOwwl5QE',
    appId: '1:872488541859:android:3ef7abff830c490cae6916',
    messagingSenderId: '872488541859',
    projectId: 'my-ecom-cr007',
    storageBucket: 'my-ecom-cr007.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB81Bgy6aP4GzSxCHabKXta5O3Rohu8oQk',
    appId: '1:872488541859:ios:71549c27d5d1ccf1ae6916',
    messagingSenderId: '872488541859',
    projectId: 'my-ecom-cr007',
    storageBucket: 'my-ecom-cr007.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB81Bgy6aP4GzSxCHabKXta5O3Rohu8oQk',
    appId: '1:872488541859:ios:71549c27d5d1ccf1ae6916',
    messagingSenderId: '872488541859',
    projectId: 'my-ecom-cr007',
    storageBucket: 'my-ecom-cr007.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS02rM9SjAkUrkkqVegagZcIJUsHHQeOE',
    appId: '1:872488541859:web:bc561c8a0265b85eae6916',
    messagingSenderId: '872488541859',
    projectId: 'my-ecom-cr007',
    authDomain: 'my-ecom-cr007.firebaseapp.com',
    storageBucket: 'my-ecom-cr007.firebasestorage.app',
  );
}
